<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [9]:
#To verify numpy has been imported and check version
print(np.__version__)

1.16.4


In [10]:
my_list = [-17,0,4,5,9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [12]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [16]:
my_tuple = (14,-3,54,5+7j)
array_from_tuple = np.array(my_tuple)
array_from_tuple #all numbers will be upgraded the most compley data type in the tuple

array([14.+0.j, -3.+0.j, 54.+0.j,  5.+7.j])

### Difference between Python and numpy data structures

In [18]:
array_from_tuple * 6

array([ 84. +0.j, -18. +0.j, 324. +0.j,  30.+42.j])