# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [2]:
np.__version__

'1.16.4'

### Display array elements in reverse order

In [5]:
array = np.arange(10)+1
np.flip(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [6]:
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Triple elements in array

In [7]:
triple = array * 3
print(triple)

[ 3  6  9 12 15 18 21 24 27 30]


### Create array with 20 zeros; every fifth element equals four

In [41]:
zeros = np.zeros(20)
zeros[0::2] = 4
print(zeros)

[4. 0. 4. 0. 4. 0. 4. 0. 4. 0. 4. 0. 4. 0. 4. 0. 4. 0. 4. 0.]


### Transpose the rows and columns

In [14]:
zeros.T

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

In [16]:
np.transpose(zeros)

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

In [20]:
matrix = np.arange(12).reshape(3,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
matrix.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
np.transpose(matrix)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Create a 5x5 identity matrix with integer components

In [23]:
my_matrix = np.asmatrix(np.eye(5,dtype='int'))
my_matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [28]:
random_data = np.random.rand(30)
random_data.mean() 

0.4647010818520153

#### Repeat, and visually estimate the mean for the sum of the two means

In [32]:
random_data_2 = np.random.rand(30)
random_data_2.mean()

0.5229044914181838

### Create an 8x8 checker board with alternating zeros and ones

In [45]:
board = np.zeros((8,8),dtype=int)
board[1::2,::2]=1
board[::2,1::2]=1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Create a sorted vector that contain 'n' random numbers

In [70]:
vector = np.random.rand(10)
sorted_vector = np.sort(vector)
sorted_vector

array([0.06, 0.11, 0.11, 0.2 , 0.43, 0.45, 0.49, 0.63, 0.84, 0.97])

### Without sorting, replace largest element in random array with the value 1234

In [71]:
vector 
        

array([0.84, 0.97, 0.43, 0.49, 0.63, 0.11, 0.45, 0.2 , 0.11, 0.06])

In [72]:
vector[vector.argmax()] = 1234
vector


array([8.43e-01, 1.23e+03, 4.26e-01, 4.89e-01, 6.32e-01, 1.12e-01,
       4.51e-01, 1.96e-01, 1.06e-01, 6.14e-02])

### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [74]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [75]:
camelot_structured_array = np.array(camelot_values,dtype=camelot_dtype)
camelot_sorted = np.sort(camelot_structured_array,order='height')
for n in np.arange(camelot_sorted.size):
    print(camelot_sorted[n])

(b'Galahad', 1.7, 38)
(b'Arthur', 1.8, 41)
(b'Lancelot', 1.9, 38)


### Make an array read-only (immutable)

In [76]:
my_ordinary = np.array(np.arange(12))
my_ordinary.flags.writeable = False
my_ordinary[3] = 1

ValueError: assignment destination is read-only

### Print enumerated values from a 3x3 NumPy array

In [81]:
my_3_3 = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(my_3_3):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
