<h1>Broadcasting</h1>

In [2]:
import numpy as np

In [3]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [4]:
#shape
my_3D_array.shape

(2, 7, 5)

In [5]:
#number of dimensions
my_3D_array.ndim

3

In [6]:
#size, number of elements
my_3D_array.size

70

In [7]:
# data type for each element
my_3D_array.dtype

dtype('int32')

In [8]:
5 * my_3D_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [19]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))
print("left_mat: \n",left_mat)
print("right_mat: \n",right_mat)


left_mat: 
 [[0 1 2]
 [3 4 5]]
right_mat: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
np.inner(left_mat,right_mat) # Will throw an error because np.inner is for one dimensinal arrays

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [24]:
np.dot(left_mat,right_mat) #this will work because if for

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### numpy.inner(a, b)

Inner product of two arrays.

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.inner.html?highlight=inner#numpy.inner

### numpy.dot(a, b, out=None)

Dot product of two arrays. Specifically,

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

* If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

* If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

* If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

* If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b

https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html?highlight=dot

### Operations along axes

In [25]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [26]:
my_3D_array.shape

(2, 7, 5)

In [27]:
my_3D_array.sum()

2415

In [28]:
(69 * 70)/2

2415.0

In [29]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [30]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [31]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [33]:
my_2D_array = np.ones(35,dtype="int_").reshape((7,5))*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [34]:
my_random_2D_array = np.random.random((7,5))
my_random_2D_array

array([[0.85071635, 0.6994527 , 0.75396633, 0.58143371, 0.5424824 ],
       [0.44247385, 0.84082547, 0.76416569, 0.63855615, 0.91128895],
       [0.81727439, 0.98063009, 0.48137405, 0.75192713, 0.95335957],
       [0.9824308 , 0.28454077, 0.18811813, 0.77431686, 0.04197018],
       [0.84948966, 0.62988414, 0.07791959, 0.74124358, 0.32346086],
       [0.92516225, 0.81367512, 0.43430696, 0.45899976, 0.60068651],
       [0.4540271 , 0.47853471, 0.80992749, 0.75164263, 0.01269347]])

In [36]:
np.set_printoptions(precision=4) # set floating point up to 4 spaces
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.6995,  1.5079,  1.7443,  2.1699],
        [ 2.2124,  5.045 ,  5.3492,  5.1084,  8.2016],
        [ 8.1727, 10.7869,  5.7765,  9.7751, 13.347 ],
        [14.7365,  4.5527,  3.198 , 13.9377,  0.7974],
        [16.9898, 13.2276,  1.7142, 17.0486,  7.7631],
        [23.1291, 21.1556, 11.7263, 12.852 , 17.4199],
        [13.6208, 14.8346, 25.9177, 24.8042,  0.4316]],

       [[29.7751, 25.1803, 27.8968, 22.0945, 21.1568],
        [17.699 , 34.4738, 32.095 , 27.4579, 40.0967],
        [36.7773, 45.109 , 22.6246, 36.0925, 46.7146],
        [49.1215, 14.5116,  9.7821, 41.0388,  2.2664],
        [46.7219, 35.2735,  4.4414, 42.9921, 19.0842],
        [55.5097, 49.6342, 26.927 , 28.917 , 38.4439],
        [29.5118, 31.5833, 54.2651, 51.1117,  0.8758]]])

In [37]:
my_vector = np.arange(5) * 7 
my_vector[0] = 1
my_vector

array([ 1,  7, 14, 21, 28])

In [38]:
my_3D_array / my_vector

array([[[ 0.    ,  0.1429,  0.1429,  0.1429,  0.1429],
        [ 5.    ,  0.8571,  0.5   ,  0.381 ,  0.3214],
        [10.    ,  1.5714,  0.8571,  0.619 ,  0.5   ],
        [15.    ,  2.2857,  1.2143,  0.8571,  0.6786],
        [20.    ,  3.    ,  1.5714,  1.0952,  0.8571],
        [25.    ,  3.7143,  1.9286,  1.3333,  1.0357],
        [30.    ,  4.4286,  2.2857,  1.5714,  1.2143]],

       [[35.    ,  5.1429,  2.6429,  1.8095,  1.3929],
        [40.    ,  5.8571,  3.    ,  2.0476,  1.5714],
        [45.    ,  6.5714,  3.3571,  2.2857,  1.75  ],
        [50.    ,  7.2857,  3.7143,  2.5238,  1.9286],
        [55.    ,  8.    ,  4.0714,  2.7619,  2.1071],
        [60.    ,  8.7143,  4.4286,  3.    ,  2.2857],
        [65.    ,  9.4286,  4.7857,  3.2381,  2.4643]]])

In [39]:
my_3D_array % my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]], dtype=int32)