<h2>Intrinsic NumPy array creation using NumPy's methods</h2>

In [1]:
import numpy as np

In [4]:
a = np.arange(6) # will create an array of 6 numbers, starting at 0
a

array([0, 1, 2, 3, 4, 5])

In [7]:
b = np.arange(10,23) #will create an array from 10 to 23
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [8]:
len(b) 

13

In [9]:
b.size

13

In [11]:
c = np.arange(10,23,5)#start at 10, end at 23, step of 5
c

array([10, 15, 20])

In [13]:
d = np.arange(10,26,5)
d

array([10, 15, 20, 25])

In [17]:
e = np.arange(0,26,step=5) #deleting the start at 0 will return the same array
e

array([ 0,  5, 10, 15, 20, 25])