# Joining and Splitting Arrays
- concatenate
- stack
- split


In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
a

array([[1, 2],
       [3, 4]])

In [3]:
b

array([[5, 6]])

In [5]:
together = np.concatenate((a,b),axis=0)
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
together.shape

(3, 2)

In [8]:
together[1,1] = 555
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [9]:
a

array([[1, 2],
       [3, 4]])

In [10]:
c = np.array([[1,2],[3,4]])*3+5
c

array([[ 8, 11],
       [14, 17]])

In [11]:
np.concatenate((a,c),axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [13]:
arrays = np.zeros((5,3,4))
for n in range(5):
    arrays[n] = np.random.rand(3,4)
arrays

array([[[0.63714542, 0.62903057, 0.87236373, 0.12880355],
        [0.44387527, 0.99828283, 0.75395839, 0.41490155],
        [0.36525125, 0.44539383, 0.48610237, 0.77761015]],

       [[0.62491023, 0.78131278, 0.44887362, 0.28467223],
        [0.25267281, 0.9094427 , 0.22852442, 0.00155402],
        [0.85723974, 0.60382648, 0.2730019 , 0.45178151]],

       [[0.18309017, 0.56568828, 0.58811124, 0.17837482],
        [0.42663091, 0.20499416, 0.50846456, 0.51801714],
        [0.16092012, 0.35427617, 0.50042211, 0.21076884]],

       [[0.67916794, 0.22482793, 0.89295358, 0.5386721 ],
        [0.06717054, 0.59157546, 0.72801835, 0.44627294],
        [0.95803651, 0.85270037, 0.23871158, 0.91922641]],

       [[0.03776121, 0.87652827, 0.39328186, 0.36874878],
        [0.01003166, 0.82377378, 0.69980656, 0.27265703],
        [0.23110512, 0.49646191, 0.74732808, 0.17873164]]])

In [15]:
stack0 = np.stack(arrays,axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays,axis=2)

In [16]:
stack0

array([[[0.63714542, 0.62903057, 0.87236373, 0.12880355],
        [0.44387527, 0.99828283, 0.75395839, 0.41490155],
        [0.36525125, 0.44539383, 0.48610237, 0.77761015]],

       [[0.62491023, 0.78131278, 0.44887362, 0.28467223],
        [0.25267281, 0.9094427 , 0.22852442, 0.00155402],
        [0.85723974, 0.60382648, 0.2730019 , 0.45178151]],

       [[0.18309017, 0.56568828, 0.58811124, 0.17837482],
        [0.42663091, 0.20499416, 0.50846456, 0.51801714],
        [0.16092012, 0.35427617, 0.50042211, 0.21076884]],

       [[0.67916794, 0.22482793, 0.89295358, 0.5386721 ],
        [0.06717054, 0.59157546, 0.72801835, 0.44627294],
        [0.95803651, 0.85270037, 0.23871158, 0.91922641]],

       [[0.03776121, 0.87652827, 0.39328186, 0.36874878],
        [0.01003166, 0.82377378, 0.69980656, 0.27265703],
        [0.23110512, 0.49646191, 0.74732808, 0.17873164]]])

In [17]:
stack1

array([[[0.63714542, 0.62903057, 0.87236373, 0.12880355],
        [0.62491023, 0.78131278, 0.44887362, 0.28467223],
        [0.18309017, 0.56568828, 0.58811124, 0.17837482],
        [0.67916794, 0.22482793, 0.89295358, 0.5386721 ],
        [0.03776121, 0.87652827, 0.39328186, 0.36874878]],

       [[0.44387527, 0.99828283, 0.75395839, 0.41490155],
        [0.25267281, 0.9094427 , 0.22852442, 0.00155402],
        [0.42663091, 0.20499416, 0.50846456, 0.51801714],
        [0.06717054, 0.59157546, 0.72801835, 0.44627294],
        [0.01003166, 0.82377378, 0.69980656, 0.27265703]],

       [[0.36525125, 0.44539383, 0.48610237, 0.77761015],
        [0.85723974, 0.60382648, 0.2730019 , 0.45178151],
        [0.16092012, 0.35427617, 0.50042211, 0.21076884],
        [0.95803651, 0.85270037, 0.23871158, 0.91922641],
        [0.23110512, 0.49646191, 0.74732808, 0.17873164]]])

In [18]:
stack2

array([[[0.63714542, 0.62491023, 0.18309017, 0.67916794, 0.03776121],
        [0.62903057, 0.78131278, 0.56568828, 0.22482793, 0.87652827],
        [0.87236373, 0.44887362, 0.58811124, 0.89295358, 0.39328186],
        [0.12880355, 0.28467223, 0.17837482, 0.5386721 , 0.36874878]],

       [[0.44387527, 0.25267281, 0.42663091, 0.06717054, 0.01003166],
        [0.99828283, 0.9094427 , 0.20499416, 0.59157546, 0.82377378],
        [0.75395839, 0.22852442, 0.50846456, 0.72801835, 0.69980656],
        [0.41490155, 0.00155402, 0.51801714, 0.44627294, 0.27265703]],

       [[0.36525125, 0.85723974, 0.16092012, 0.95803651, 0.23110512],
        [0.44539383, 0.60382648, 0.35427617, 0.85270037, 0.49646191],
        [0.48610237, 0.2730019 , 0.50042211, 0.23871158, 0.74732808],
        [0.77761015, 0.45178151, 0.21076884, 0.91922641, 0.17873164]]])

In [19]:
temp = np.arange(5)
np.split(temp,1)

[array([0, 1, 2, 3, 4])]

In [20]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [21]:
s0 = np.split(before_split,5,axis=0)
s0

[array([[[0.63714542, 0.62903057, 0.87236373, 0.12880355],
         [0.44387527, 0.99828283, 0.75395839, 0.41490155],
         [0.36525125, 0.44539383, 0.48610237, 0.77761015]]]),
 array([[[0.62491023, 0.78131278, 0.44887362, 0.28467223],
         [0.25267281, 0.9094427 , 0.22852442, 0.00155402],
         [0.85723974, 0.60382648, 0.2730019 , 0.45178151]]]),
 array([[[0.18309017, 0.56568828, 0.58811124, 0.17837482],
         [0.42663091, 0.20499416, 0.50846456, 0.51801714],
         [0.16092012, 0.35427617, 0.50042211, 0.21076884]]]),
 array([[[0.67916794, 0.22482793, 0.89295358, 0.5386721 ],
         [0.06717054, 0.59157546, 0.72801835, 0.44627294],
         [0.95803651, 0.85270037, 0.23871158, 0.91922641]]]),
 array([[[0.03776121, 0.87652827, 0.39328186, 0.36874878],
         [0.01003166, 0.82377378, 0.69980656, 0.27265703],
         [0.23110512, 0.49646191, 0.74732808, 0.17873164]]])]

In [22]:
type(s0)

list

In [24]:
s0[1]

array([[[0.62491023, 0.78131278, 0.44887362, 0.28467223],
        [0.25267281, 0.9094427 , 0.22852442, 0.00155402],
        [0.85723974, 0.60382648, 0.2730019 , 0.45178151]]])

In [25]:
s0[1].shape

(1, 3, 4)

In [26]:
s1 = np.split(before_split,3,axis=1)
s1

[array([[[0.63714542, 0.62903057, 0.87236373, 0.12880355]],
 
        [[0.62491023, 0.78131278, 0.44887362, 0.28467223]],
 
        [[0.18309017, 0.56568828, 0.58811124, 0.17837482]],
 
        [[0.67916794, 0.22482793, 0.89295358, 0.5386721 ]],
 
        [[0.03776121, 0.87652827, 0.39328186, 0.36874878]]]),
 array([[[0.44387527, 0.99828283, 0.75395839, 0.41490155]],
 
        [[0.25267281, 0.9094427 , 0.22852442, 0.00155402]],
 
        [[0.42663091, 0.20499416, 0.50846456, 0.51801714]],
 
        [[0.06717054, 0.59157546, 0.72801835, 0.44627294]],
 
        [[0.01003166, 0.82377378, 0.69980656, 0.27265703]]]),
 array([[[0.36525125, 0.44539383, 0.48610237, 0.77761015]],
 
        [[0.85723974, 0.60382648, 0.2730019 , 0.45178151]],
 
        [[0.16092012, 0.35427617, 0.50042211, 0.21076884]],
 
        [[0.95803651, 0.85270037, 0.23871158, 0.91922641]],
 
        [[0.23110512, 0.49646191, 0.74732808, 0.17873164]]])]

In [27]:
s2 = np.split(before_split,4,axis=2)
s2

[array([[[0.63714542],
         [0.44387527],
         [0.36525125]],
 
        [[0.62491023],
         [0.25267281],
         [0.85723974]],
 
        [[0.18309017],
         [0.42663091],
         [0.16092012]],
 
        [[0.67916794],
         [0.06717054],
         [0.95803651]],
 
        [[0.03776121],
         [0.01003166],
         [0.23110512]]]), array([[[0.62903057],
         [0.99828283],
         [0.44539383]],
 
        [[0.78131278],
         [0.9094427 ],
         [0.60382648]],
 
        [[0.56568828],
         [0.20499416],
         [0.35427617]],
 
        [[0.22482793],
         [0.59157546],
         [0.85270037]],
 
        [[0.87652827],
         [0.82377378],
         [0.49646191]]]), array([[[0.87236373],
         [0.75395839],
         [0.48610237]],
 
        [[0.44887362],
         [0.22852442],
         [0.2730019 ]],
 
        [[0.58811124],
         [0.50846456],
         [0.50042211]],
 
        [[0.89295358],
         [0.72801835],
         [0.23871158