<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [3]:
import numpy as np #creates 9 elements equally spaced, starts at 9 and ends at 15

In [2]:
np.linspace(5,15,9)#creates 9 elements equally spaced, starts at 9 and ends at 15

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

The difference between arange() and linspace() is that the end parameter is included in the array with linspace but not necessarily with arange

In [4]:
my_linspace = np.linspace(5,15,9,retstep=True)
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

### Documentation
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

retstep : bool, optional 

If True, return (samples, step), where step is the spacing between samples.

 https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace

In [6]:
my_linspace[1] #return the spacing between samples

1.25

### zeros()

In [7]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

### ones()

In [10]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [15]:
c = np.zeros((5,4)) #passing a touple (A,B) with create an array of A by B
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
d = np.zeros((5,4,3)) # 5 two dimensional arrays, 4 groups of matrixes, 3 columns
d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Note:
* arange: returns integers
* linspace, ones and zeros: return floarting points

You can use the dtype argument to indicate the data type

In [19]:
e = np.zeros(11,dtype='int64')
e

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [22]:
f = np.zeros(11) #will return an array of default data type 
f

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])