# Finding Pattern

In [1]:
import numpy as np

## Given this array, find the next number in the sequence

In [2]:
my_teaser_array = np.array([1, 7, 19, 37, 61, 91, 127, 169, 217, 271, 331])
my_teaser_array

array([  1,   7,  19,  37,  61,  91, 127, 169, 217, 271, 331])

In [7]:
np.diff(my_teaser_array)

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [8]:
np.diff(my_teaser_array,n=2)

array([6, 6, 6, 6, 6, 6, 6, 6, 6])

In [9]:
np.diff(my_teaser_array,n=3)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
from sympy import init_session
init_session()

IPython console for SymPy 1.4 (Python 3.7.3-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.4/



In [12]:
diff(x**3)

In [13]:
diff(x**3,x,2)

In [14]:
diff(x**3,x,3)

In [17]:
diff(x**3,x,4)

In [18]:
def my_guess(n):
    return (n+1)**3 - n**3

In [19]:
my_guess(np.arange(20))

array([   1,    7,   19,   37,   61,   91,  127,  169,  217,  271,  331,
        397,  469,  547,  631,  721,  817,  919, 1027, 1141], dtype=int32)