# Views and Copies

In [1]:
import numpy as np

In [2]:
mi_casa = np.array([-45,-31,-12,0,2,25,51,99])

In [3]:
su_casa = mi_casa

### Same or Different

In [5]:
#reference equallity
mi_casa is su_casa

True

In [7]:
id(mi_casa)

2029639847648

In [8]:
id(su_casa)

2029639847648

In [9]:
# value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
su_casa[4] = 1010

In [11]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [12]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [24]:
tree_house = np.array([-45,-31,-12,0,2,25,51,99])

In [25]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [26]:
id(tree_house)

2029672848000

In [27]:
id(mi_casa)

2029639847648

In [28]:
tree_house[0] = 214

In [29]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [30]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [31]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [32]:
tree_house is mi_casa

False

### View: shallow copy

In [33]:
farm_house = tree_house.view()
farm_house.shape = (2,4)

In [34]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [36]:
tree_house[3]=-111
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

### Deep Copy

In [37]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [38]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])